import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — UFSL',
  description: 'Privacy policy for UFSL — Ultimate Fantasy Sports League.',
}

export default function PrivacyPage() {
  return (
    <article className="prose prose-invert prose-sm sm:prose-base max-w-none">
      <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-brand-muted text-sm mb-8">Last updated: March 2026</p>

      <section className="mb-8">
        <p className="text-brand-muted leading-relaxed">
          UFSL (Ultimate Fantasy Sports League), accessible at <strong className="text-white">ufsl.net</strong>, is
          committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share
          your information when you use our platform.
        </p>
        <p className="text-brand-muted leading-relaxed mt-3">
          Questions? Contact us at{' '}
          <a href="mailto:shawn@progotta.com" className="text-brand-orange hover:underline">
            shawn@progotta.com
          </a>
          .
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">1. Information We Collect</h2>
        <p className="text-brand-muted leading-relaxed mb-3">
          We collect information you provide directly and information generated by your use of UFSL:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-brand-muted">
          <li>
            <strong className="text-white">Name &amp; Email Address</strong> — provided at registration,
            used to identify your account and send important platform communications.
          </li>
          <li>
            <strong className="text-white">Phone Number</strong> — optional, collected when you enable
            SMS notifications. Used only to send bracket alerts and reminders.
          </li>
          <li>
            <strong className="text-white">Bracket Picks &amp; Pool Activity</strong> — your picks,
            scores, standings, and pool participation history.
          </li>
          <li>
            <strong className="text-white">Payment Information</strong> — when you pay pool entry fees.
            Payment card details are processed and stored by Stripe; UFSL does not store raw card numbers.
          </li>
          <li>
            <strong className="text-white">Device &amp; Usage Data</strong> — IP address, browser type,
            pages visited, and feature usage, collected automatically via standard web server logs and
            session cookies.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">2. How We Use Your Information</h2>
        <ul className="list-disc pl-5 space-y-2 text-brand-muted">
          <li>Operate and improve the UFSL platform — pools, leaderboards, scoring, and notifications.</li>
          <li>Send transactional emails (account verification, payment receipts, bracket confirmations).</li>
          <li>Send SMS alerts for picks deadlines, round results, and standings — only if you opt in.</li>
          <li>Process entry-fee payments for bracket pools.</li>
          <li>Detect and prevent fraud, abuse, and violations of our Terms of Service.</li>
          <li>Comply with legal obligations.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">3. How We Share Your Information</h2>
        <p className="text-brand-muted leading-relaxed mb-3">
          We do not sell your personal information. We share data only with the following trusted
          service providers who process it on our behalf:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-brand-muted">
          <li>
            <strong className="text-white">Stripe</strong> — payment processing. Stripe&apos;s privacy
            policy: <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="text-brand-orange hover:underline">stripe.com/privacy</a>
          </li>
          <li>
            <strong className="text-white">Twilio</strong> — SMS delivery. Phone numbers are transmitted
            to Twilio solely to deliver opt-in text messages. Twilio&apos;s privacy policy:{' '}
            <a href="https://www.twilio.com/legal/privacy" target="_blank" rel="noopener noreferrer" className="text-brand-orange hover:underline">twilio.com/legal/privacy</a>
          </li>
          <li>
            <strong className="text-white">Resend</strong> — transactional email delivery.
          </li>
          <li>
            <strong className="text-white">Supabase</strong> — database and authentication infrastructure.
            Your data is stored in Supabase&apos;s managed PostgreSQL hosted on AWS.
          </li>
          <li>
            <strong className="text-white">Vercel</strong> — hosting and edge delivery.
          </li>
        </ul>
        <p className="text-brand-muted leading-relaxed mt-3">
          We may also disclose information if required by law or to protect the rights, property, or
          safety of UFSL, our users, or the public.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">4. Cookies &amp; Tracking</h2>
        <p className="text-brand-muted leading-relaxed">
          UFSL uses basic session cookies to keep you logged in and maintain your preferences. We do not
          use third-party advertising cookies or tracking pixels. You can disable cookies in your browser
          settings, but doing so may break certain features.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">5. Data Retention</h2>
        <p className="text-brand-muted leading-relaxed">
          We retain your account data as long as your account is active. If you delete your account,
          we will remove your personal information within 30 days, except where required by law to retain
          records (e.g., payment transaction records, which are retained for 7 years).
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">6. Your Rights</h2>
        <p className="text-brand-muted leading-relaxed mb-3">
          Depending on your location, you may have the following rights:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-brand-muted">
          <li>
            <strong className="text-white">Access &amp; Portability</strong> — request a copy of the
            data we hold about you.
          </li>
          <li>
            <strong className="text-white">Correction</strong> — request we correct inaccurate data.
          </li>
          <li>
            <strong className="text-white">Deletion</strong> — delete your account from{' '}
            <strong className="text-white">Settings → Account → Delete Account</strong>, or email us.
          </li>
          <li>
            <strong className="text-white">Opt Out of SMS</strong> — reply <strong className="text-white">STOP</strong>{' '}
            to any UFSL text, or disable SMS in{' '}
            <a href="/profile/notifications" className="text-brand-orange hover:underline">
              /profile/notifications
            </a>
            .
          </li>
        </ul>
        <p className="text-brand-muted leading-relaxed mt-3">
          To exercise any of these rights, contact{' '}
          <a href="mailto:shawn@progotta.com" className="text-brand-orange hover:underline">
            shawn@progotta.com
          </a>
          .
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">7. GDPR &amp; CCPA</h2>
        <p className="text-brand-muted leading-relaxed">
          If you are located in the European Union or California, you have additional rights under GDPR
          and the California Consumer Privacy Act (CCPA) respectively, including the right to know what
          data we collect, the right to delete, and the right to opt out of the &quot;sale&quot; of your
          personal data (we do not sell data). Contact us to exercise these rights.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">8. Children&apos;s Privacy</h2>
        <p className="text-brand-muted leading-relaxed">
          UFSL is intended for users 13 years of age and older. We do not knowingly collect personal
          information from children under 13. If you believe a child has provided us personal information,
          contact us and we will delete it promptly.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-white mb-3">9. Changes to This Policy</h2>
        <p className="text-brand-muted leading-relaxed">
          We may update this Privacy Policy from time to time. We will notify you of significant changes
          by posting the new policy on this page with an updated date and, where appropriate, via email.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">10. Contact</h2>
        <p className="text-brand-muted leading-relaxed">
          UFSL — Ultimate Fantasy Sports League<br />
          <a href="https://ufsl.net" className="text-brand-orange hover:underline">ufsl.net</a><br />
          <a href="mailto:shawn@progotta.com" className="text-brand-orange hover:underline">shawn@progotta.com</a>
        </p>
      </section>
    </article>
  )
}
